### ISSUE TITLE
Enviar esborrany

### ISSUE THREAD

**Issue by jmirfern** [jmirfern/data-lifecycle-pr2#8]
Enviar esborrany del PDF al professor

**Comment by jmirfern** [comment]
Hola @mp334t1, ja he fusionat a `main`. Podries enviar esborrany al professor? Sinó pots ja ho faig jo. No oblidis posar-me en copia si ho fas. Merci!

**Comment by mp334t1** [comment]
Enviat, esperem al feedback.

**Comment by mp334t1** [comment]
Feedback rebut, esta en el correu.
